---

version: '3'

tasks:
  prune:
    desc: prune
    cmds:
      - docker system prune -af
  build:
    desc: build
    cmds:
      - docker compose up --build
  up:
    desc: up
    cmds:
      - docker compose up
  default:
    desc: List commands
    cmds:
      - task -l
    silent: true
